export const FESTIVALS = {
  'psb-2026': {
    id: 'psb-2026',
    name: 'Primavera Sound',
    city: 'Barcelona',
    fullName: 'Primavera Sound Barcelona',
    dates: '5–8 Jun 2026',
    start: '2026-06-05',
    end: '2026-06-08',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
      { value: 'sunday', label: 'Sun' },
    ],
    artists: [
      'Addison Rae', 'Agriculture', 'Alex G', 'Amaarae', 'Amiga Date Cuenta',
      'Anna von Hausswolff', 'Annahstasia', 'Arca', 'Ashnikko',
      'Bad Gyal', 'Barry B', 'Baxter Dury', 'Beverly Glenn-Copeland and Elizabeth Copeland',
      'Big Thief', 'Blood Orange', 'Blond:ish', 'Brutalismus 3000', 'Buscabulla',
      'Cameron Winter', 'Carl Cox', 'Caroline', 'Cobrah', 'Corte!',
      'Debit', 'deBasement', 'Depresión Sonora', 'Dijon', 'Disobey',
      'DJ Marcelle', 'DJ Nobu', 'DJ Playero', 'Doja Cat',
      'Einstürzende Neubauten', 'Ethel Cain',
      'Fcukers', 'Femtanyl', 'Florence Road', 'Four Tet',
      'Geese', 'Gisela João', 'Gorillaz', 'Grace Ives', 'Guitarricadelafuente',
      'Haloplus+', 'Hannah Diamond',
      'JADE', 'Joey Valence & Brae', 'Joseph Capriati',
      'Kneecap', 'Knocked Loose', 'Kylesa',
      'Lambrini Girls', 'Léa Sen', 'Little Simz', 'Lola Young', 'Lucrecia Dalt',
      'Mac DeMarco', 'Marina', 'Massive Attack', 'Melt-Banana', 'Men I Trust',
      'Merzbow', 'Mina Galán', 'Mobilegirl', 'Mogwai', 'Mohammad Reza Mortazavi',
      'My Bloody Valentine',
      'Oklou', 'Olivia Rodrigo', 'Osserp', 'Overmono',
      'Panda Bear', 'Peggy Gou', 'PinkPantheress',
      'Ralphie Choo', 'Raya Diplomática', 'Renaldo & Clara', 'Rilo Kiley',
      'Rojuu', 'Rusowsky', 'Rustie',
      'Safety Trance', 'Skrillex', 'Slowdive', 'Smerz', 'Sudan Archives',
      'The Avalanches', 'The Cure', 'The New Eves', 'The Sophs', 'The xx',
      'These New Puritans', 'Touché Amoré', 'TV Girl',
      'Underground Resistance',
      "Ven'nus", 'Viagra Boys',
      'Wet Leg',
      'Yard Act',
      '¥ØU$UK€ ¥UK1MAT$U',
    ],
  },
  'psp-2026': {
    id: 'psp-2026',
    name: 'Primavera Sound',
    city: 'Porto',
    fullName: 'Primavera Sound Porto',
    dates: '11–14 Jun 2026',
    start: '2026-06-11',
    end: '2026-06-14',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
      { value: 'sunday', label: 'Sun' },
    ],
    artists: [
      'Agriculture', 'Aiko el grupo', 'Amaarae', 'Annahstasia',
      'Bad Gyal', 'Baxter Dury', 'Big Thief', 'Black Country, New Road', 'Buscabulla',
      'Capicua', 'Dijon',
      'Emmy Curl', 'Ethel Cain',
      'Gelli Haha', 'Gisela João', 'Gorillaz',
      'IDLES', 'Inês Marques Lucas',
      'JADE', 'Joey Valence & Brae',
      'Kneecap',
      'Mari Froes', 'Mark William Lewis', 'Massive Attack', 'Melt-Banana',
      'NAPA', 'Nation of Language', 'Ninajirachi',
      'Oklou',
      'Panda Bear', 'PAUS', 'Peggy Gou',
      'Rita Vian', 'Rusowsky',
      'Sensible Soccers', 'Slowdive', 'Smerz', 'Sudan Archives', 'SuM',
      'Texas Is the Reason', 'The New Eves', 'The xx', 'Triángulo de Amor Bizarro',
      'Vaiapraia', 'Viagra Boys',
      'Water From Your Eyes',
      'Xinobi',
      'Yard Act',
    ],
  },
  'vida-2026': {
    id: 'vida-2026',
    name: 'Vida Festival',
    city: 'Vilanova i la Geltrú',
    fullName: 'Vida Festival',
    dates: '2–4 Jul 2026',
    start: '2026-07-02',
    end: '2026-07-04',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
    ],
    artists: [
      'Al·lèrgiques al Pol·len', 'Alavedra', 'Alcalá Norte', 'Aldous Harding', 'Amaia', 'Amaia Miranda', 'Amore', 'Ángeles Toledano', 'Azuleja',
      'Balu Brigada', 'Barry B',
      'Carmen Lancho', 'Cassius', 'Charlotte Cardin', 'Clara Peya', 'Cupido',
      'Dan Peralbo i El Comboi', 'Depresión Sonora',
      'Edna Bravo', 'El Petit de Cal Eril i La Processó Metafísica',
      'Fades', 'Fatboy Slim', 'Ferran Palau', 'Frente Cumbiero',
      'Gazella', 'Greta', 'Guitarricadelafuente',
      'Henrio', 'Indus',
      'Juan Wauters',
      'Kiliki',
      'La Ludwig Band', 'La LOM', 'La Paloma', 'La Tania', 'Las Petunias', 'Lavanda', 'Lecocq', 'Lewis OfMan', 'Lia Kali', 'Llum',
      'Maig', 'Maria Arnal', 'Maria Jaume', 'Me and The Bees', 'Modern Woman', 'Mujeres', 'Myd',
      'Nu Genea (Live Band)',
      'Osees',
      'Preen',
      'Ralphie Choo', 'Remei de Ca la Fresca', 'Roserona',
      'Saint Etienne', 'Sam Berridge', 'shame', 'Sidonie', 'Sunday (1994)', 'SVSTO',
      'Triquell', 'TRISTÁN!', 'Tversky', 'Tyler Ballgame',
      'Yerai Cortés', 'Yellow', 'Yung Prado',
    ],
  },
  'kappa-2026': {
    id: 'kappa-2026',
    name: 'Kappa Futurfestival',
    city: 'Torino',
    fullName: 'Kappa Futurfestival',
    dates: '3–5 Jul 2026',
    start: '2026-07-03',
    end: '2026-07-05',
    days: [
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
      { value: 'sunday', label: 'Sun' },
    ],
    artists: [
      'Adiel B2B Quest', 'Adrian Mills', 'Agoria', 'Amelie Lens', 'Anthea', 'Anxhela', 'Argy', 'Armin van Buuren', 'Avalan Rokston', 'Avalon Emerson',
      'Batu', 'Beatrice M.', 'Ben Klock B2B Marcel Dettmann', 'Boys Noize',
      'Carl Craig ft. Mike Banks', 'Charlotte de Witte', 'Chez Damier', 'Chris Lake', 'Clara Cuvé', 'Cloudy', 'Cuartero',
      'D-Leria pres. Kongas', 'Daphni', 'Dawn Patrol', 'Diplo B2B Busy P B2B Tatyana Jane', 'Disclosure', 'DJ Rush', 'DJRUM', 'Drums and Chant', 'DYEN',
      'Enrico Sangiuliano', 'Erol Alkan B2B Confidence Man DJs',
      'Fiorella', 'Fireground', 'Floating Points', 'Floating Points B2B Palms Trax', 'Four Tet', 'Four Tet B2B Skrillex',
      'Gandalf', 'Greg Willen B2B Sizing',
      'Interplanetary Criminal',
      'Jamie Jones B2B Joseph Capriati B2B Seth Troxler', 'Jane Fitz', 'Jane Fitz B2B Rhadoo', 'Jazzy', 'Joe Claussell', 'John Talabot',
      'Ki/Ki', 'Konduku B2B Marco Shuttle',
      'Lil Louis',
      'Maceo Plex', 'Mad Dog', 'Mala', 'Manda Moor B2B Cuartero', 'Massano', 'Max Cooper', 'Max Dean B2B Luke Dean', 'Mia Koden', 'Michael Bibi', 'Miss Monique', 'Mochakk',
      'Nicola Gavino', 'Nikolina', 'Nosedrip', 'Novah',
      'Objekt', 'Olympe', 'Onlynumbers',
      'Paco Osuna B2B Nicole Moudaber', 'Peggy Gou', 'Prunk B2B YOUniverse',
      'Redrago', 'Restricted', 'Rhadoo', 'Richie Hawtin', 'Riverside',
      'Sammy Virji', 'Sebastian Ingrosso', 'Serafina B2B Fumi', 'Seth Troxler', 'Shkedul B2B Enrico Vivaldi', 'Simone de Kunovich', 'Skream B2B Fleur Shore', 'Solomun', 'STOOR Live', 'Sven Väth',
      'Tal Fussman', 'The Robinson', 'Tini Gessler', 'Toxic Machinery',
      'Vieze Asbak', 'Viviana Casanova',
      'Wade', 'Wah Wah Wino',
      'Xiaolin',
    ],
  },
  'nos-alive-2026': {
    id: 'nos-alive-2026',
    name: 'NOS Alive',
    city: 'Lisboa',
    fullName: 'NOS Alive',
    dates: '9–11 Jul 2026',
    start: '2026-07-09',
    end: '2026-07-11',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
    ],
    artists: [
      'A Perfect Circle', 'Alabama Shakes', 'Alessi Rose', 'Arthi',
      'Barry Can\'t Swim', 'Ben Böhmer', 'Bia Ferreira', 'Black Country, New Road', 'Branko', 'Buraka Som Sistema',
      'Caiiro', 'Caribou', 'Central Cee', 'Chris Luno', 'CMAT',
      'David Bruno', 'Deize Tigrona', 'Digitalism', 'Dogstar', 'Don West',
      'Father John Misty', 'Fidju Kitxora', 'Fiona Kraft', 'Florence + The Machine', 'Florence Road', 'Foo Fighters',
      'Gary Clark Jr.', 'Girl in Red', 'Glass Animals',
      'Heartworms', 'High Vis',
      'Iolanda',
      'Jalen Ngonda', 'Jazzy', 'Jehnny Beth', 'Jordan Rakei', 'Justice',
      'L\'Impératrice', 'La Fleur', 'Lorde', 'Luísa Sonza',
      'Macacos do Chinês', 'Malu Magalhães', 'Marcin', 'Martha Da\'ro', 'Matt Berninger', 'Mazes', 'MJ Nebreda', 'Mochakk', 'Modeselektor', 'Mundo Segundo & Sam The Kid',
      'Nathy Peluso', 'Nick Cave & The Bad Seeds', 'Nininho Vaz Maia', 'No Guidnce', 'Noiserv',
      'Palaye Royale', 'Panda Bear', 'Parov Stelar', 'Pedro da Linha', 'Pixies', 'Polo & Pan', 'Primal Scream', 'Pulp',
      'Samuel Úria', 'Saya Noé', 'SBTRKT', 'Skunk Anansie', 'Sonya', 'Stresshead',
      'T-Rex', 'Teddy Swims', 'The Backseat Lovers', 'The Bloody Beetroots', 'The Reytons', 'The Royston Club', 'The Teskey Brothers', 'The War on Drugs', 'The Warning', 'The Wombats', 'TOMORA', 'Tontom', 'Trophy Wife', 'Tyla', 'Twenty One Pilots',
      'WET BED GANG', 'Wolf Alice',
      'Xinobi',
      'Yakuza', 'Yamê', 'Yazz Ahmed', 'Yendry',
      'Zara Larsson', 'Zimmer90',
    ],
  },
  'bbk-2026': {
    id: 'bbk-2026',
    name: 'Bilbao BBK Live',
    city: 'Bilbao',
    fullName: 'Bilbao BBK Live',
    dates: '9–11 Jul 2026',
    start: '2026-07-09',
    end: '2026-07-11',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
    ],
    artists: [
      '2manydjs',
      'AIMARZ', 'Alabama Shakes', 'Alexis Le-Tan', 'Amelia Holt', 'Amore', 'Apparat',
      'Badsista', 'BARRRK', 'BASHKKA', 'BB Trickz', 'Belén Aguilera', 'Belle and Sebastian',
      'Calvin Harris', 'Cervatana', 'Charlotte de Witte', 'CMAT',
      'Dani Fernández', 'David Byrne', 'Dee Diggs', 'Dellafuente', 'Depresión Sonora', 'DJ Koze', 'DJ Nobu', 'Don West', 'Donato Dozzy',
      'Elena Barker', 'Erol Alkan B2B Optimo (Espacio)',
      'Fatoumata Diawara', 'FKA twigs', 'Folk Bitch Trio',
      'GAR', 'Genosidra', 'Guim',
      'Hemlocke Springs', 'Hoonine', 'horsegiirL', 'Hotcore Party: Taichu and Friends',
      'IDLES', 'Interpol', 'IRO AKA',
      'James Massiah', 'Joni DJ', 'Juicy BAE',
      'La M.O.D.A.', 'La Paloma', 'Las Petunias', 'Lily Allen', 'Livwutang',
      'Marte Lasarte', 'Mattias El Mansouri', 'Meritxell de Soto', 'Mietze Conte', 'Mind Enterprises', 'Miravalles',
      'Nicolas Lutz', 'Nu Genea Live',
      'Paris Paloma', 'Paula Tape',
      'Queralt Lahoz',
      'Ralphie Choo', 'Richie Hawtin', 'Robbie Williams',
      'Sara Zozaya', 'Sedef Adasï', 'SOMADAMANTINA', 'Soulwax', 'Suave', 'Suze Ijó',
      'Thee Sacred Souls', 'TOMORA', 'Torus',
      'Vampirina Club by Metrika & D.Basto', 'Vlada',
      'Westside Cowboy',
      'Xoel López',
      'Yerai Cortés', 'YLIA',
      'ZAZ',
    ],
  },
  'opener-2026': {
    id: 'opener-2026',
    name: "Open'er Festival",
    city: 'Gdynia',
    fullName: "Open'er Festival",
    dates: '1–4 Jul 2026',
    start: '2026-07-01',
    end: '2026-07-04',
    days: [
      { value: 'wednesday', label: 'Wed' },
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
    ],
    artists: [
      'Addison Rae', 'Anna Calvi', 'Audrey Nuna', 'Avi',
      'Bassvictim', 'Błoto', 'Bokka',
      'Calvin Harris', 'Clipse', 'Coals',
      'Daniel Godson', 'Daria Ze Śląska', 'David Byrne', 'Dezydery', 'Don West', 'Drabusheyka',
      'Ethel Cain',
      'Florence + The Machine',
      'Halsey', 'Hela', 'horsegiirL', 'Hubert.', 'Hyphen Dash',
      'IDLES',
      'JADE', 'Jehnny Beth', 'Jennie', 'Joy (Anonymous)', 'Just Mustard',
      'Kasia Lins', 'Kasia Sienkiewicz', 'Kaz Bałagane', 'Klawo', 'Kneecap', 'Koza & Kuba Więcek',
      'Lordofon', 'LP', 'Luvcat', 'Łaszewo',
      'maks.tachasiuk', 'Martin Garrix', 'Matt Berninger',
      'Natalia Muianga', 'Nick Cave & The Bad Seeds',
      'Oki', 'Omasta',
      'Panda Bear & Sonic Boom', 'Peggy Gou', 'PinkPantheress', 'Pixy',
      'RALPH KAMINSKI & MY BEST BAND IN THE WORLD', 'René', 'Reneé Rapp',
      'Sadie Jean', 'Skok', 'Slowdive', 'Sobel', 'Sofi Tukker', 'Sokół', 'supermodel*', 'Sw@da & Niczos',
      'Teddy Swims', 'The Cure', 'The xx', 'TOMORA',
      'Viagra Boys', 'Vito Bambino',
      '¥ØU$UK€ ¥UK1MAT$U',
      'Zalia', 'Zara Larsson',
    ],
  },
};

export const FESTIVAL_LIST = Object.values(FESTIVALS).sort((a, b) => a.fullName.localeCompare(b.fullName));
export const DEFAULT_FESTIVAL_ID = 'psb-2026';
