export const FESTIVALS = {
  'psb-2026': {
    id: 'psb-2026',
    name: 'Primavera Sound',
    city: 'Barcelona',
    fullName: 'Primavera Sound Barcelona',
    dates: '5–8 Jun 2026',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
      { value: 'sunday', label: 'Sun' },
    ],
    artists: [
      'Addison Rae', 'Agriculture', 'Alex G', 'Amaarae', 'Amiga Date Cuenta',
      'Anna von Hausswolff', 'Annahstasia', 'Arca', 'Ashnikko',
      'Bad Gyal', 'Barry B', 'Baxter Dury', 'Beverly Glenn-Copeland and Elizabeth Copeland',
      'Big Thief', 'Blood Orange', 'Blond:ish', 'Brutalismus 3000', 'Buscabulla',
      'Cameron Winter', 'Carl Cox', 'Caroline', 'Cobrah', 'Corte!',
      'Debit', 'deBasement', 'Depresión Sonora', 'Dijon', 'Disobey',
      'DJ Marcelle', 'DJ Nobu', 'DJ Playero', 'Doja Cat',
      'Einstürzende Neubauten', 'Ethel Cain',
      'Fcukers', 'Femtanyl', 'Florence Road', 'Four Tet',
      'Geese', 'Gisela João', 'Gorillaz', 'Grace Ives', 'Guitarricadelafuente',
      'Haloplus+', 'Hannah Diamond',
      'JADE', 'Joey Valence & Brae', 'Joseph Capriati',
      'Kneecap', 'Knocked Loose', 'Kylesa',
      'Lambrini Girls', 'Léa Sen', 'Little Simz', 'Lola Young', 'Lucrecia Dalt',
      'Mac DeMarco', 'Marina', 'Massive Attack', 'Melt-Banana', 'Men I Trust',
      'Merzbow', 'Mina Galán', 'Mobilegirl', 'Mogwai', 'Mohammad Reza Mortazavi',
      'My Bloody Valentine',
      'Oklou', 'Olivia Rodrigo', 'Osserp', 'Overmono',
      'Panda Bear', 'Peggy Gou', 'PinkPantheress',
      'Ralphie Choo', 'Raya Diplomática', 'Renaldo & Clara', 'Rilo Kiley',
      'Rojuu', 'Rusowsky', 'Rustie',
      'Safety Trance', 'Skrillex', 'Slowdive', 'Smerz', 'Sudan Archives',
      'The Avalanches', 'The Cure', 'The New Eves', 'The Sophs', 'The xx',
      'These New Puritans', 'Touché Amoré', 'TV Girl',
      'Underground Resistance',
      "Ven'nus", 'Viagra Boys',
      'Wet Leg',
      'Yard Act',
      '¥ØU$UK€ ¥UK1MAT$U',
    ],
  },
  'psp-2026': {
    id: 'psp-2026',
    name: 'Primavera Sound',
    city: 'Porto',
    fullName: 'Primavera Sound Porto',
    dates: '11–14 Jun 2026',
    days: [
      { value: 'thursday', label: 'Thu' },
      { value: 'friday', label: 'Fri' },
      { value: 'saturday', label: 'Sat' },
      { value: 'sunday', label: 'Sun' },
    ],
    artists: [
      'Agriculture', 'Aiko el grupo', 'Amaarae', 'Annahstasia',
      'Bad Gyal', 'Baxter Dury', 'Big Thief', 'Black Country, New Road', 'Buscabulla',
      'Capicua', 'Dijon',
      'Emmy Curl', 'Ethel Cain',
      'Gelli Haha', 'Gisela João', 'Gorillaz',
      'IDLES', 'Inês Marques Lucas',
      'JADE', 'Joey Valence & Brae',
      'Kneecap',
      'Mari Froes', 'Mark William Lewis', 'Massive Attack', 'Melt-Banana',
      'NAPA', 'Nation of Language', 'Ninajirachi',
      'Oklou',
      'Panda Bear', 'PAUS', 'Peggy Gou',
      'Rita Vian', 'Rusowsky',
      'Sensible Soccers', 'Slowdive', 'Smerz', 'Sudan Archives', 'SuM',
      'Texas Is the Reason', 'The New Eves', 'The xx', 'Triángulo de Amor Bizarro',
      'Vaiapraia', 'Viagra Boys',
      'Water From Your Eyes',
      'Xinobi',
      'Yard Act',
    ],
  },
};

export const FESTIVAL_LIST = Object.values(FESTIVALS);
export const DEFAULT_FESTIVAL_ID = 'psb-2026';
